/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportedRouteImport } from './routes/imported'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as CallIdRouteImport } from './routes/call.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportedRoute = ImportedRouteImport.update({
  id: '/imported',
  path: '/imported',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const CallIdRoute = CallIdRouteImport.update({
  id: '/call/$id',
  path: '/call/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imported': typeof ImportedRoute
  '/tests': typeof TestsRoute
  '/call/$id': typeof CallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imported': typeof ImportedRoute
  '/tests': typeof TestsRoute
  '/call/$id': typeof CallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/imported': typeof ImportedRoute
  '/tests': typeof TestsRoute
  '/call/$id': typeof CallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/imported' | '/tests' | '/call/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/imported' | '/tests' | '/call/$id'
  id: '__root__' | '/' | '/imported' | '/tests' | '/call/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportedRoute: typeof ImportedRoute
  TestsRoute: typeof TestsRoute
  CallIdRoute: typeof CallIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imported': {
      id: '/imported'
      path: '/imported'
      fullPath: '/imported'
      preLoaderRoute: typeof ImportedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$id': {
      id: '/call/$id'
      path: '/call/$id'
      fullPath: '/call/$id'
      preLoaderRoute: typeof CallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportedRoute: ImportedRoute,
  TestsRoute: TestsRoute,
  CallIdRoute: CallIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
